# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/add_singer_dialog_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(483, 389)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.singer_name_line = QtWidgets.QLineEdit(Dialog)
        self.singer_name_line.setObjectName("singer_name_line")
        self.gridLayout.addWidget(self.singer_name_line, 0, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.stores_image_location_lbl = QtWidgets.QLabel(Dialog)
        self.stores_image_location_lbl.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.stores_image_location_lbl.setObjectName("stores_image_location_lbl")
        self.gridLayout.addWidget(self.stores_image_location_lbl, 1, 2, 1, 1)
        self.browse_image_btn = QtWidgets.QToolButton(Dialog)
        self.browse_image_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.browse_image_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.browse_image_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/add_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse_image_btn.setIcon(icon)
        self.browse_image_btn.setIconSize(QtCore.QSize(50, 50))
        self.browse_image_btn.setAutoRaise(True)
        self.browse_image_btn.setObjectName("browse_image_btn")
        self.gridLayout.addWidget(self.browse_image_btn, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.stores_songs_location_lbl = QtWidgets.QLabel(Dialog)
        self.stores_songs_location_lbl.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.stores_songs_location_lbl.setObjectName("stores_songs_location_lbl")
        self.gridLayout.addWidget(self.stores_songs_location_lbl, 2, 2, 1, 1)
        self.browse_songs_btn = QtWidgets.QToolButton(Dialog)
        self.browse_songs_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.browse_songs_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.browse_songs_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/browse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse_songs_btn.setIcon(icon1)
        self.browse_songs_btn.setIconSize(QtCore.QSize(50, 50))
        self.browse_songs_btn.setAutoRaise(True)
        self.browse_songs_btn.setObjectName("browse_songs_btn")
        self.gridLayout.addWidget(self.browse_songs_btn, 2, 3, 1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setMinimumSize(QtCore.QSize(120, 35))
        self.cancel_btn.setMaximumSize(QtCore.QSize(120, 35))
        self.cancel_btn.setStyleSheet("border:2px solid #EE3E54;\n"
"font: 14pt \"Times New Roman\";\n"
"border-radius:10px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_btn.setIcon(icon2)
        self.cancel_btn.setIconSize(QtCore.QSize(30, 30))
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_3.addWidget(self.cancel_btn)
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        self.ok_btn.setMinimumSize(QtCore.QSize(120, 35))
        self.ok_btn.setMaximumSize(QtCore.QSize(120, 35))
        self.ok_btn.setStyleSheet("border:2px solid #78A2D2;\n"
"font: 14pt \"Times New Roman\";\n"
"border-radius:10px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ok_btn.setIcon(icon3)
        self.ok_btn.setIconSize(QtCore.QSize(30, 30))
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout_3.addWidget(self.ok_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Singer"))
        self.label.setText(_translate("Dialog", "Singer Name"))
        self.label_3.setText(_translate("Dialog", "Singer Image Path"))
        self.stores_image_location_lbl.setText(_translate("Dialog", "location...."))
        self.label_2.setText(_translate("Dialog", "Songs Location"))
        self.stores_songs_location_lbl.setText(_translate("Dialog", "location...."))
        self.cancel_btn.setText(_translate("Dialog", "Cancel"))
        self.ok_btn.setText(_translate("Dialog", "Ok"))
import app_resource_rc
