# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/main_page_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(998, 764)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(120, 100))
        self.label.setMaximumSize(QtCore.QSize(120, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/app_icon.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setStyleSheet("font: 75 18pt \"Times New Roman\";\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.add_singer_btn = QtWidgets.QPushButton(Form)
        self.add_singer_btn.setMinimumSize(QtCore.QSize(200, 50))
        self.add_singer_btn.setMaximumSize(QtCore.QSize(200, 50))
        self.add_singer_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.add_singer_btn.setStyleSheet("border:3px solid #FCE0A2;\n"
"font: 14pt \"Times New Roman\";\n"
"border-radius:10px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_singer_btn.setIcon(icon)
        self.add_singer_btn.setIconSize(QtCore.QSize(50, 50))
        self.add_singer_btn.setObjectName("add_singer_btn")
        self.horizontalLayout.addWidget(self.add_singer_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 958, 522))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.singer_buttons_layout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.singer_buttons_layout.setObjectName("singer_buttons_layout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.log_out_btn = QtWidgets.QToolButton(Form)
        self.log_out_btn.setMinimumSize(QtCore.QSize(50, 70))
        self.log_out_btn.setMaximumSize(QtCore.QSize(50, 70))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_out_btn.setIcon(icon1)
        self.log_out_btn.setIconSize(QtCore.QSize(50, 50))
        self.log_out_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.log_out_btn.setAutoRaise(True)
        self.log_out_btn.setObjectName("log_out_btn")
        self.horizontalLayout_2.addWidget(self.log_out_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Music World"))
        self.add_singer_btn.setText(_translate("Form", " Add Singer  "))
        self.groupBox.setTitle(_translate("Form", "Singers"))
        self.log_out_btn.setText(_translate("Form", "Log Out"))
import app_resource_rc
