# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/singer_info_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(555, 708)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet(".QFrame\n"
"{\n"
"border:2px solid rgb(85, 170, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.singer_image_lbl = QtWidgets.QLabel(self.frame)
        self.singer_image_lbl.setMinimumSize(QtCore.QSize(150, 200))
        self.singer_image_lbl.setMaximumSize(QtCore.QSize(150, 200))
        self.singer_image_lbl.setText("")
        self.singer_image_lbl.setPixmap(QtGui.QPixmap(":/icons/icons/im.jpg"))
        self.singer_image_lbl.setScaledContents(True)
        self.singer_image_lbl.setObjectName("singer_image_lbl")
        self.horizontalLayout.addWidget(self.singer_image_lbl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.singer_name_lbl = QtWidgets.QLabel(self.frame)
        self.singer_name_lbl.setAutoFillBackground(True)
        self.singer_name_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.singer_name_lbl.setObjectName("singer_name_lbl")
        self.verticalLayout.addWidget(self.singer_name_lbl)
        self.songs_num_lbl = QtWidgets.QLabel(self.frame)
        self.songs_num_lbl.setAutoFillBackground(True)
        self.songs_num_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.songs_num_lbl.setObjectName("songs_num_lbl")
        self.verticalLayout.addWidget(self.songs_num_lbl)
        spacerItem2 = QtWidgets.QSpacerItem(20, 237, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.frame)
        spacerItem3 = QtWidgets.QSpacerItem(20, 167, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.singer_name_lbl.setText(_translate("Form", "Singer name"))
        self.songs_num_lbl.setText(_translate("Form", "30"))
import app_resource_rc
