# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\song_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(405, 108)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet(".QFrame\n"
"{\n"
"border:2px solid rgb(85, 170, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.song_name_lpl = QtWidgets.QLabel(self.frame)
        self.song_name_lpl.setMaximumSize(QtCore.QSize(16777215, 25))
        self.song_name_lpl.setStyleSheet("\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.song_name_lpl.setLineWidth(1)
        self.song_name_lpl.setScaledContents(False)
        self.song_name_lpl.setWordWrap(False)
        self.song_name_lpl.setObjectName("song_name_lpl")
        self.horizontalLayout.addWidget(self.song_name_lpl)
        self.time_slider = QtWidgets.QSlider(self.frame)
        self.time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.time_slider.setObjectName("time_slider")
        self.horizontalLayout.addWidget(self.time_slider)
        self.play_pause_btn = QtWidgets.QToolButton(self.frame)
        self.play_pause_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.play_pause_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.play_pause_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play_pause_btn.setAutoFillBackground(True)
        self.play_pause_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/play_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_pause_btn.setIcon(icon)
        self.play_pause_btn.setIconSize(QtCore.QSize(45, 45))
        self.play_pause_btn.setAutoRaise(True)
        self.play_pause_btn.setObjectName("play_pause_btn")
        self.horizontalLayout.addWidget(self.play_pause_btn)
        self.volume_slider = QtWidgets.QSlider(self.frame)
        self.volume_slider.setEnabled(True)
        self.volume_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.volume_slider.setAutoFillBackground(False)
        self.volume_slider.setProperty("value", 99)
        self.volume_slider.setTracking(True)
        self.volume_slider.setOrientation(QtCore.Qt.Vertical)
        self.volume_slider.setInvertedAppearance(False)
        self.volume_slider.setInvertedControls(False)
        self.volume_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.volume_slider.setTickInterval(0)
        self.volume_slider.setObjectName("volume_slider")
        self.horizontalLayout.addWidget(self.volume_slider)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.song_name_lpl.setText(_translate("Form", "Amr diab - hello world"))
        self.play_pause_btn.setShortcut(_translate("Form", "Space"))
import app_resource_rc
